version: '3.8'
services:
  db:
    container_name: postgres
    image: postgres
    ports:
      - '5433:5432'
    networks:
      - forumapi_network
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: forumapi
  app:
    container_name: app
    networks:
      - forumapi_network
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - PGHOST=postgres
      - PGUSER=developer
      - PGDATABASE=forumapi
      - PGPASSWORD=supersecretpassword
      - PGPORT=5433
      - ACCESS_TOKEN_KEY=8b7b4ef375716ab08b2a3951b29d52fc00b1c855f9d1a847229b8c5935bef56d9d271e76a9cf08e614300395c3b90ebe559cf968a0741b18c9505549394b2c70
      - REFRESH_TOKEN_KEY=5078605e074a462b1460608fcbe0d0963c644402e04ad334455ff5a856cb43fd99825861dde02957d5e3184c90c532ca7d0249df20fe93d535632f3d11be7bad
      - ACCCESS_TOKEN_AGE=3000
      - HOST=localhost
      - PORT=5000
    depends_on:
      - db

networks:
  forumapi_network:
    name: forumapi_network