version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: forumapi
