name: Continuous Integration
 
on: 
    pull_request:
        branches:
            - master
 
jobs:
    build:
        runs-on: ubuntu-latest

        # services:
        #     postgres:
        #         image: postgres
        #         env:
        #             POSTGRES_USER: developer
        #             POSTGRES_PASSWORD: supersecretpassword
        #             POSTGRES_DB: forumapi_test
        #         ports:
        #             - 5434:5432
        #         options: >-
        #             --health-cmd pg_isready
        #             --health-interval 10s
        #             --health-timeout 5s
        #             --health-retries 5
        
        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Set up Node.js
                uses: actions/setup-node@v2
                with:
                  node-version: 14

            -   name: npm install migrate and test
                run: |
                    npm install
                    npm run migrate up
                    npm run test
                env:
                    CI: true
                    PGHOST_TEST: ${{ secrets.PGHOST_TEST }}
                    PGUSER_TEST: ${{ secrets.PGUSER_TEST }}
                    PGDATABASE_TEST: ${{ secrets.PGDATABASE_TEST }}
                    PGPASSWORD_TEST: ${{ secrets.PGPASSWORD_TEST }}
                    PGPORT_TEST: ${{ secrets.PGPORT_TEST }}
                    PGHOST: ${{ secrets.PGHOST_TEST }}
                    PGUSER: ${{ secrets.PGUSER_TEST }}
                    PGDATABASE: ${{ secrets.PGDATABASE_TEST }}
                    PGPASSWORD: ${{ secrets.PGPASSWORD_TEST }}
                    PGPORT: ${{ secrets.PGPORT_TEST }}
                    ACCESS_TOKEN_KEY: ${{ secrets.ACCESS_TOKEN_KEY }}
                    REFRESH_TOKEN_KEY: ${{ secrets.REFRESH_TOKEN_KEY }}
                    # POSTGRES_HOST: postgres
                    # POSTGRES_PORT: 5433